### ISSUE TITLE
CAMBIO DE CREDENCIALES URGENTE!

### ISSUE THREAD

**Issue by ElLucho74** [ElLucho74/castro_parcial_2#6]
@ingreyeslara 
Que tal buenos dias maestro, le informo que otra vez el servidor ftp esta fallando no admite ninguna de las contraseñas pasadas, la primera que me paso que no funciono y la segunda de Castro_2024 tampoco funciona, podria cambiar la contraseña otra vez por favor?

ATTE. T.S.U. Luis Castro Iturbide - Jefe del departamento de IT de ElLucho's Corp.

**Comment by ingreyeslara** [comment]
Estamos checando su acceso:

puede pasarme captura de pantalla con los datos que esta ingresando

**Comment by ElLucho74** [comment]
ftp.projectsutd.online
u614968815.ellucho74
Castro_2024

**Comment by ElLucho74** [comment]
Se cancela el problema, ya me informo uno de mis empleados que la contraseña era Parcial_2

**Comment by ingreyeslara** [comment]
errror
![castro](https://github.com/ElLucho74/castro_parcial_2/assets/75334788/6ebab1d4-aaf5-4b0d-8708-3866a5da409b)
